# Generated by Django 4.0.6 on 2022-07-31 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарии к тренировке'),
        ),
    ]
