# Generated by Django 4.0.6 on 2022-07-31 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trainings', '0002_alter_training_comment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='training',
            unique_together={('user', 'date')},
        ),
        migrations.CreateModel(
            name='ExerciseSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps_plan', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Запланированное количество повторений')),
                ('reps_fact', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Фактическое количество повторений')),
                ('weight_plan', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Запланированный вес')),
                ('weight_fact', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Фактический вес')),
                ('done', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='exercises.exercise', verbose_name='Упражнение')),
            ],
            options={
                'verbose_name': 'Подход',
                'verbose_name_plural': 'Подходы',
            },
        ),
    ]
