# Generated by Django 4.0.6 on 2022-07-31 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0004_training_sets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exerciseset',
            old_name='done',
            new_name='is_done',
        ),
    ]
